<?php

use Illuminate\Database\Seeder;

class DeplacementsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        DB::table('deplacements')->insert([
            ['destination' => 'Ait Amira' , 'type_deplacement_id' => '3'],
            ['destination' => 'Sidi Bibi' , 'type_deplacement_id' => '3'],
            ['destination' => 'Imi Mqourn' , 'type_deplacement_id' => '3'],
            ['destination' => 'Sidi Boushab' , 'type_deplacement_id' => '3'],
            ['destination' => 'Oued Essafa' , 'type_deplacement_id' => '3'],
            ['destination' => 'Belfaa' , 'type_deplacement_id' => '3'],
            ['destination' => 'Inchaden' , 'type_deplacement_id' => '3'],
            ['destination' => 'Massa' , 'type_deplacement_id' => '3'],
            ['destination' => 'Sidi Ouassay' , 'type_deplacement_id' => '3'],
            ['destination' => 'Ait Milk' , 'type_deplacement_id' => '3'],
            ['destination' => 'Ait Mzal' , 'type_deplacement_id' => '3'],
            ['destination' => 'Hilala' , 'type_deplacement_id' => '3'],
            ['destination' => 'Tassegdelt' , 'type_deplacement_id' => '3'],
            ['destination' => 'Ait Ouadrim' , 'type_deplacement_id' => '3'],
            ['destination' => 'Sidi Abdellah el Bouchouari' , 'type_deplacement_id' => '3'],
            ['destination' => 'Tanalt' , 'type_deplacement_id' => '3'],
            ['destination' => 'Ouagnez' , 'type_deplacement_id' => '3'],
            ['destination' => 'Targua Ntouchka' , 'type_deplacement_id' => '3'],
            ['destination' => 'Ida Ougnidif' , 'type_deplacement_id' => '3'],
            ['destination' => 'Tizi Ntakoucht' , 'type_deplacement_id' => '3'],
            ['destination' => 'Agadir Ida-Outanane' , 'type_deplacement_id' => '2'],
            ['destination' => 'Inezgane-Ait Melloul' , 'type_deplacement_id' => '2'],
            ['destination' => 'Taroudant' , 'type_deplacement_id' => '2'],
            ['destination' => 'Tata' , 'type_deplacement_id' => '2'],
            ['destination' => 'Tiznit' , 'type_deplacement_id' => '2'],
            ['destination' => 'Tanger-Assilah' , 'type_deplacement_id' => '1'],
            ['destination' => 'M\'diq-Fnideq' , 'type_deplacement_id' => '1'],
            ['destination' => 'Tétouan' , 'type_deplacement_id' => '1'],
            ['destination' => 'Fahs-Anjra' , 'type_deplacement_id' => '1'],
            ['destination' => 'Larache' , 'type_deplacement_id' => '1'],
            ['destination' => 'Al Hoceïma' , 'type_deplacement_id' => '1'],
            ['destination' => 'Chefchaouen' , 'type_deplacement_id' => '1'],
            ['destination' => 'Ouezzane' , 'type_deplacement_id' => '1'],
            ['destination' => 'Oujda-Angad' , 'type_deplacement_id' => '1'],
            ['destination' => 'Nador' , 'type_deplacement_id' => '1'],
            ['destination' => 'Driouch' , 'type_deplacement_id' => '1'],
            ['destination' => 'Jerada' , 'type_deplacement_id' => '1'],
            ['destination' => 'Berkane' , 'type_deplacement_id' => '1'],
            ['destination' => 'Taourirt' , 'type_deplacement_id' => '1'],
            ['destination' => 'Guercif' , 'type_deplacement_id' => '1'],
            ['destination' => 'Figuig' , 'type_deplacement_id' => '1'],
            ['destination' => 'Fès' , 'type_deplacement_id' => '1'],
            ['destination' => 'Meknès' , 'type_deplacement_id' => '1'],
            ['destination' => 'El Hajeb' , 'type_deplacement_id' => '1'],
            ['destination' => 'Ifrane' , 'type_deplacement_id' => '1'],
            ['destination' => 'Moulay Yaâcoub' , 'type_deplacement_id' => '1'],
            ['destination' => 'Séfrou' , 'type_deplacement_id' => '1'],
            ['destination' => 'Boulemane' , 'type_deplacement_id' => '1'],
            ['destination' => 'Taounate' , 'type_deplacement_id' => '1'],
            ['destination' => 'Taza' , 'type_deplacement_id' => '1'],
            ['destination' => 'Rabat' , 'type_deplacement_id' => '1'],
            ['destination' => 'Salé' , 'type_deplacement_id' => '1'],
            ['destination' => 'Skhirate-Témara' , 'type_deplacement_id' => '1'],
            ['destination' => 'Kénitra' , 'type_deplacement_id' => '1'],
            ['destination' => 'Khémisset' , 'type_deplacement_id' => '1'],
            ['destination' => 'Sidi Kacem' , 'type_deplacement_id' => '1'],
            ['destination' => 'Sidi Slimane' , 'type_deplacement_id' => '1'],
            ['destination' => 'Béni-Mellal' , 'type_deplacement_id' => '1'],
            ['destination' => 'Azilal' , 'type_deplacement_id' => '1'],
            ['destination' => 'Fquih Ben Salah' , 'type_deplacement_id' => '1'],
            ['destination' => 'Khénifra' , 'type_deplacement_id' => '1'],
            ['destination' => 'Khouribga' , 'type_deplacement_id' => '1'],
            ['destination' => 'Casablanca' , 'type_deplacement_id' => '1'],
            ['destination' => 'Mohammédia' , 'type_deplacement_id' => '1'],
            ['destination' => 'El Jadida' , 'type_deplacement_id' => '1'],
            ['destination' => 'Nouaceur' , 'type_deplacement_id' => '1'],
            ['destination' => 'Médiouna' , 'type_deplacement_id' => '1'],
            ['destination' => 'Benslimane' , 'type_deplacement_id' => '1'],
            ['destination' => 'Berrechid' , 'type_deplacement_id' => '1'],
            ['destination' => 'Settat' , 'type_deplacement_id' => '1'],
            ['destination' => 'Sidi Bennour' , 'type_deplacement_id' => '1'],
            ['destination' => 'Marrakech' , 'type_deplacement_id' => '1'],
            ['destination' => 'Chichaoua' , 'type_deplacement_id' => '1'],
            ['destination' => 'Al Haouz' , 'type_deplacement_id' => '1'],
            ['destination' => 'El Kelaâ des Sraghna' , 'type_deplacement_id' => '1'],
            ['destination' => 'Essaouira' , 'type_deplacement_id' => '1'],
            ['destination' => 'Rehamna' , 'type_deplacement_id' => '1'],
            ['destination' => 'Safi' , 'type_deplacement_id' => '1'],
            ['destination' => 'Youssoufia' , 'type_deplacement_id' => '1'],
            ['destination' => 'Errachidia' , 'type_deplacement_id' => '1'],
            ['destination' => 'Ouarzazate' , 'type_deplacement_id' => '1'],
            ['destination' => 'Midelt' , 'type_deplacement_id' => '1'],
            ['destination' => 'Tinghir' , 'type_deplacement_id' => '1'],
            ['destination' => 'Zagora' , 'type_deplacement_id' => '1'],
            ['destination' => 'Guelmim' , 'type_deplacement_id' => '1'],
            ['destination' => 'Assa-Zag' , 'type_deplacement_id' => '1'],
            ['destination' => 'Tan-Tan' , 'type_deplacement_id' => '1'],
            ['destination' => 'Sidi Ifni' , 'type_deplacement_id' => '1'],
            ['destination' => 'Laâyoune' , 'type_deplacement_id' => '1'],
            ['destination' => 'Boujdour' , 'type_deplacement_id' => '1'],
            ['destination' => 'Tarfaya' , 'type_deplacement_id' => '1'],
            ['destination' => 'Es-Semara' , 'type_deplacement_id' => '1'],
            ['destination' => 'Oued Ed Dahab' , 'type_deplacement_id' => '1'],
            ['destination' => 'Aousserd' , 'type_deplacement_id' => '1']
        ]);
    }
}
